# Generated by Django 4.2.20 on 2025-05-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionlike",
            name="value",
            field=models.SmallIntegerField(default=1),
        ),
    ]
