# Generated by Django 4.2.20 on 2025-05-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_questionlike_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerlike",
            name="value",
            field=models.SmallIntegerField(default=1),
        ),
    ]
